package in.wilsonl.nanoscript.Parsing;

public enum TokenType {

    T_KEYWORD_FROM,
    T_KEYWORD_IMPORT,
    T_KEYWORD_EXPORT,
    T_KEYWORD_AS,

    T_KEYWORD_CLASS,
    T_KEYWORD_CLASS_END,

    T_KEYWORD_FUNCTION,
    T_KEYWORD_FUNCTION_END,
    T_KEYWORD_METHOD,
    T_KEYWORD_METHOD_END,
    T_KEYWORD_CONSTRUCTOR,
    T_KEYWORD_CONSTRUCTOR_END,

    T_KEYWORD_SELF,
    T_KEYWORD_STATIC,
    T_KEYWORD_SUPER,
    T_KEYWORD_FINAL,
    T_KEYWORD_SEALED,

    T_KEYWORD_THROW,

    T_KEYWORD_AND,
    T_KEYWORD_OR,
    T_KEYWORD_NOT,
    T_KEYWORD_IN,
    T_KEYWORD_IS,
    T_KEYWORD_ASCENDS,
    T_KEYWORD_DESCENDS,

    T_IDENTIFIER,
    T_LITERAL_STRING,
    T_LITERAL_NUMBER,
    T_LITERAL_BOOLEAN,
    T_LITERAL_NULL,

    T_KEYWORD_IF,
    T_KEYWORD_THEN,
    T_KEYWORD_ELSEIF,
    T_KEYWORD_OTHERWISE,
    T_KEYWORD_ENDIF,
    T_KEYWORD_ELIF,
    T_KEYWORD_ELSE,
    T_KEYWORD_FI,

    T_KEYWORD_REPEAT,
    T_KEYWORD_UNTIL,
    T_KEYWORD_LOOP,
    T_KEYWORD_WHILE,
    T_KEYWORD_BEFORE,
    T_KEYWORD_AFTER,

    T_KEYWORD_FOR,
    T_KEYWORD_FOR_END,
    T_KEYWORD_DO,

    T_KEYWORD_CASE,
    T_KEYWORD_CASE_END,
    T_KEYWORD_WHEN,

    T_KEYWORD_RETURN,
    T_KEYWORD_BREAK,
    T_KEYWORD_NEXT,

    T_KEYWORD_BEGIN,
    T_KEYWORD_END,

    T_KEYWORD_TRY,
    T_KEYWORD_CATCH,
    T_KEYWORD_TRY_END,

    T_HASH,

    T_PARENTHESIS_LEFT,
    T_PARENTHESIS_RIGHT,

    T_SQUARE_BRACKET_LEFT,
    T_SQUARE_BRACKET_RIGHT,

    T_CHEVRON_LEFT,
    T_CHEVRON_RIGHT,

    T_BRACE_LEFT,
    T_BRACE_RIGHT,

    T_ARROW_LEFT,
    T_ARROW_RIGHT,

    T_ACCESSOR,
    T_NULL_ACCESSOR,
    T_NULL_LOOKUP,
    T_NULL_CALL,
    T_NULL_COALESCING,

    T_PLUS,
    T_MINUS,
    T_MULTIPLY,
    T_DIVIDE,
    T_MODULO,
    T_EXPONENTIATE,

    T_INITIALISE,
    T_ASSIGNMENT,

    T_EQ,
    T_NEQ,
    T_LEQ,
    T_GEQ,
    T_SPACESHIP,
    T_KEYWORD_INSTANCEOF,

    T_QUESTION,
    T_COLON,
    T_COMMA,
    T_SEMICOLON,

}
